export const items = [
  {
    id: 1,
    brand: "Maserati",
    model: "Ghibli",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    kms: 0,
    year: 2019,
    price: "R$00.000,00",
  },
  {
    id: 2,
    brand: "Maserati",
    model: "Ghibli",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    kms: 0,
    year: 2019,
    price: "R$00.000,00",
  },
  {
    id: 3,
    brand: "Maserati",
    model: "Ghibli",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    kms: 0,
    year: 2019,
    price: "R$00.000,00",
  },
  {
    id: 4,
    brand: "Maserati",
    model: "Ghibli",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    kms: 0,
    year: 2019,
    price: "R$00.000,00",
  },
  {
    id: 5,
    brand: "Maserati",
    model: "Ghibli",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    kms: 0,
    year: 2019,
    price: "R$00.000,00",
  },
  {
    id: 6,
    brand: "Maserati",
    model: "Ghibli",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    kms: 0,
    year: 2019,
    price: "R$00.000,00",
  },
  {
    id: 7,
    brand: "Maserati",
    model: "Ghibli",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    kms: 0,
    year: 2019,
    price: "R$00.000,00",
  },
  {
    id: 8,
    brand: "Maserati",
    model: "Ghibli",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    kms: 0,
    year: 2019,
    price: "R$00.000,00",
  },
  {
    id: 9,
    brand: "Maserati",
    model: "Ghibli",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    kms: 0,
    year: 2019,
    price: "R$00.000,00",
  },
  {
    id: 10,
    brand: "Maserati",
    model: "Ghibli",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    kms: 0,
    year: 2019,
    price: "R$00.000,00",
  },
  {
    id: 11,
    brand: "Maserati",
    model: "Ghibli",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    kms: 0,
    year: 2019,
    price: "R$00.000,00",
  },
  {
    id: 12,
    brand: "Maserati",
    model: "Ghibli",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    kms: 0,
    year: 2019,
    price: "R$00.000,00",
  },
  {
    id: 13,
    brand: "Maserati",
    model: "Ghibli",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    kms: 0,
    year: 2019,
    price: "R$00.000,00",
  },
  {
    id: 14,
    brand: "Maserati",
    model: "Ghibli",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    kms: 0,
    year: 2019,
    price: "R$00.000,00",
  },
  {
    id: 15,
    brand: "Maserati",
    model: "Ghibli",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    kms: 0,
    year: 2019,
    price: "R$00.000,00",
  },
  {
    id: 16,
    brand: "Maserati",
    model: "Ghibli",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    kms: 0,
    year: 2019,
    price: "R$00.000,00",
  },
];

export const user = {
  firstname: "Samuel",
  lastname: "Leão",
};
